## 4-е домашнее задание - Библиотека numpy

Подпишите этот блокнот: укажите ФИО и номер группы. Выполненное задание загрузите в свой репозиторий «<b>Spring2023Python</b>» в github в папку "<b>homework04</b>".  

Перед выполнением этого домашнего задания полезно прочитать про возможности и основные методы библиотеки numpy:  
http://acm.mipt.ru/twiki/bin/view/Cintro/PythonNumpy  


1.	Создайте равномерное разбиение интервала от -1.3 до 2.5 на 64 отрезка.

In [1]:
import numpy as np
def razbienie (a, b, n):
    a = np.linspace(a, b, n+1)
    return a

print(razbienie(-1.3, 2.5, 64))

[-1.3      -1.240625 -1.18125  -1.121875 -1.0625   -1.003125 -0.94375
 -0.884375 -0.825    -0.765625 -0.70625  -0.646875 -0.5875   -0.528125
 -0.46875  -0.409375 -0.35     -0.290625 -0.23125  -0.171875 -0.1125
 -0.053125  0.00625   0.065625  0.125     0.184375  0.24375   0.303125
  0.3625    0.421875  0.48125   0.540625  0.6       0.659375  0.71875
  0.778125  0.8375    0.896875  0.95625   1.015625  1.075     1.134375
  1.19375   1.253125  1.3125    1.371875  1.43125   1.490625  1.55
  1.609375  1.66875   1.728125  1.7875    1.846875  1.90625   1.965625
  2.025     2.084375  2.14375   2.203125  2.2625    2.321875  2.38125
  2.440625  2.5     ]


2.	Сгенерируйте numpy массив длины $3n$, заполненный циклически числами 1, 2, 3, 1, 2, 3, 1....

In [10]:
def create_circle_array(n):
    a = np.array([1, 2, 3]*3*n)
    return a
print(create_circle_array(1))

[1 2 3 1 2 3 1 2 3]


3.	Создайте массив первых 10 нечетных целых чисел.

In [4]:
def create_odd_array(n):
    arr = np.arange(1, 2*n, 2)
    return arr

print(create_odd_array(10))

[ 1  3  5  7  9 11 13 15 17 19]


4.  Создайте массив нулей размера 10 x 10, а затем создайте в нём "рамку" из единиц по краям.

In [15]:
def create_frame_matrix(n):
    matrix = np.zeros((n,n))
    matrix[0] = 1
    matrix[n-1] = 1
    matrix[:, 0] = 1
    matrix[:, n-1] = 1
    return matrix

print(create_frame_matrix(10))

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


5.  Создайте массив 8 x 8 с шахматной доской из нулей и единиц.

In [19]:
def create_chess_matrix(n):
    matrix = np.zeros((n,n))
    matrix[0::2, 0::2] = 1
    matrix[1::2, 1::2] = 1
    return matrix

print(create_chess_matrix(8))

[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


6.  Создайте функцию, которая создает $n×n$ матрицу с $(i,j)$-элементом, равным $i+j$.

In [21]:
def create_ij_matrix(n):
    row_indexes = np.arange(n)
    col_indexes = np.arange(n)
    return row_indexes[:, np.newaxis] + col_indexes

print(create_ij_matrix(4))

[[0 1 2 3]
 [1 2 3 4]
 [2 3 4 5]
 [3 4 5 6]]


7. Примените функцию dot для перемножения вектор на вектор, матрицу на вектор и матрицу на матрицу.

In [33]:
vector1 = np.random.randint(10, size=(5))
vector2 = np.random.randint(10, size=(5))
matrix1 = np.random.randint(10, size=(3,5))
matrix2 = np.random.randint(10, size=(5,4))


vec_x_vec = np.dot(vector1, vector2)
mat_x_vec = np.dot(matrix1, vector1)
mat_x_mat = np.dot(matrix1, matrix2)

# print('vector 1 = ', vector1)
# print('vector 2 = ', vector2)
# print('matrix 1 = \n', matrix1)
# print('matrix 2 = \n', matrix2)

print(vec_x_vec)
print(mat_x_vec)
print(mat_x_mat)

44
[ 99  43 124]
[[ 22 112  94  93]
 [ 49  22  30  62]
 [ 65 134 126 107]]


8. Вычислите cos(x) и sin(x) на интервале [0,1] с шагом $0.05$, а затем объедините оба массива чисел как строки в один массив.

In [34]:
xx = np.arange(0, 1.05, 0.05)
cos_values = np.cos(xx * np.pi)
sin_values = np.sin(xx * np.pi)

result = np.vstack((cos_values, sin_values))
print(result)

[[ 1.00000000e+00  9.87688341e-01  9.51056516e-01  8.91006524e-01
   8.09016994e-01  7.07106781e-01  5.87785252e-01  4.53990500e-01
   3.09016994e-01  1.56434465e-01  6.12323400e-17 -1.56434465e-01
  -3.09016994e-01 -4.53990500e-01 -5.87785252e-01 -7.07106781e-01
  -8.09016994e-01 -8.91006524e-01 -9.51056516e-01 -9.87688341e-01
  -1.00000000e+00]
 [ 0.00000000e+00  1.56434465e-01  3.09016994e-01  4.53990500e-01
   5.87785252e-01  7.07106781e-01  8.09016994e-01  8.91006524e-01
   9.51056516e-01  9.87688341e-01  1.00000000e+00  9.87688341e-01
   9.51056516e-01  8.91006524e-01  8.09016994e-01  7.07106781e-01
   5.87785252e-01  4.53990500e-01  3.09016994e-01  1.56434465e-01
   1.22464680e-16]]


9. Создайте матрицу $A$ размера $3×5$ из случайных чисел с равномерным распределением на отрезке $[-1,3]$ (используйте np.random.rand)

In [35]:
A = np.random.rand(3, 5) * 4 - 1

print(A)

[[-0.21759204  1.19176285  1.6805339  -0.61885453 -0.70725247]
 [ 1.2200651   0.75847949 -0.0827758   1.75779374  0.95881998]
 [ 1.48613621  2.88750761  2.21190758  0.06341742  0.22465926]]


10. Найдите сумму всех элементов, сумму внутри строк, сумму внутри столбцов, а также среднее значение, дисперсию и стандартное отклонение чисел для каждой строки матрицы $A$. (Подобно тому, как sorted имеет необязательный аргумент key=, многие функции Numpy имеют необязательный аргумент axis=)


In [39]:
sum_elems = np.sum(A)
sum_rows = np.sum(A, axis=1)
sum_cols = np.sum(A, axis=0)
mean_rows = np.mean(A, axis=1)
var_rows = np.var(A, axis=1)
std_rows = np.std(A, axis=1)

print('Сумма всех элементов: ', sum_elems)
print('Сумма внутри строк: ', sum_rows)
print('Сумма внутри столбцов: ', sum_cols)
print('Средние значения: ', mean_rows)
print('Дисперсии: ', var_rows)   
print('Стандартные отклонения: ', std_rows)    

Сумма всех элементов:  12.814608293920038
Сумма внутри строк:  [1.3285977  4.61238252 6.87362808]
Сумма внутри столбцов:  [2.48860927 4.83774995 3.80966567 1.20235662 0.47622677]
Средние значения:  [0.26571954 0.9224765  1.37472562]
Дисперсии:  [0.96439835 0.36501238 1.20879543]
Стандартные отклонения:  [0.98203786 0.60416255 1.09945233]


11.  Отнимите от каждого элемента матрицы $A$ среднее по строке и поделите на стандартное отклонение строки.

In [40]:
A_norm = (A - mean_rows[:, np.newaxis]) / std_rows[:, np.newaxis]

print(A_norm)

[[-0.49215167  0.94298127  1.44069228 -0.90075353 -0.99076834]
 [ 0.4925638  -0.27144518 -1.66387723  1.38260347  0.06015514]
 [ 0.10133281  1.37594142  0.76145363 -1.19269218 -1.04603567]]


12. Отсортируйте матрицу $A$ по 3-ому столбцу, т.е. поменяйте местами строки матрицы так, чтобы 3-й столбец оказался отсортированным. Используйте для этого slicing + argsort + indexing.

In [41]:
sort_indexes = np.argsort(A[:, 2])
A_sorted = A[sort_indexes]

print(A_sorted)

[[ 1.2200651   0.75847949 -0.0827758   1.75779374  0.95881998]
 [-0.21759204  1.19176285  1.6805339  -0.61885453 -0.70725247]
 [ 1.48613621  2.88750761  2.21190758  0.06341742  0.22465926]]


13. Посчитайте две матрицы: $B = A^TA$ и $C = AA^T$. Что вы можете о них сказать? Какого они размера? В чём их сходство и отличие?

In [42]:
B = np.dot(A.T, A) # размер матрицы 5x5
C = np.dot(A, A.T) # размер матрицы 3x3

# сходства: обе симметричные; являются произведением матрицы А и транспонированной А
# + как выяснилось позже, одинаковые суммы диагональных элементов

# отличия: размерность; 

print('B = \n', B)
print('C = \n', C)



B = 
 [[ 3.74450598  4.95730587  2.82053328  2.37352754  1.65758958]
 [ 4.95730587 10.33329003  8.32691408  0.77884094  0.53307341]
 [ 2.82053328  8.32691408  7.72358115 -1.04523534 -0.77100332]
 [ 2.37352754  0.77884094 -1.04523534  3.47684152  2.13734147]
 [ 1.65758958  0.53307341 -0.77100332  2.13734147  1.47001361]]
C = 
 [[ 5.17502614 -1.26660274  6.63690157]
 [-1.26660274  6.07987642  4.14708834]
 [ 6.63690157  4.14708834 15.49332972]]


14. Найдите сумму диагональных элементов матриц $B$ и $C$.

In [43]:
sum_B = np.trace(B)
sum_C = np.trace(C)

print('Сумма диагональных элементов матрицы B: ', sum_B)
print('Сумма диагональных элементов матрицы C: ', sum_C)

Сумма диагональных элементов матрицы B:  26.748232280235747
Сумма диагональных элементов матрицы C:  26.748232280235744


15.	Посчитайте детерминант и ранг матриц $A$, $B$ и $C$, посмотрите на спектр (набор собственных значений) матриц $B$ и $C$, какие выводы вы можете сделать?  
(подсказка: используйте готовые функции из библиотеки np.linalg). 


In [47]:
# det_A = np.linalg.det(A) матрица А неквадратная
det_B = np.linalg.det(B)
det_C = np.linalg.det(C)

rank_A = np.linalg.matrix_rank(A)
rank_B = np.linalg.matrix_rank(B)
rank_C = np.linalg.matrix_rank(C)

eigvals_B = np.linalg.eigvalsh(B)
eigvals_C = np.linalg.eigvalsh(C)

print('Детерминант матрицы B: ', det_B)
print('Детерминант матрицы C: ', det_C)
print('Ранг матрицы A: ', rank_A)
print('Ранг матрицы B: ', rank_B)
print('Ранг матрицы C: ', rank_C)
print('Спектр матрицы B: ', eigvals_B)
print('Спектр матрицы C: ', eigvals_C)

Детерминант матрицы B:  -7.138189495162811e-31
Детерминант матрицы C:  36.08444239593551
Ранг матрицы A:  3
Ранг матрицы B:  3
Ранг матрицы C:  3
Спектр матрицы B:  [-2.32254947e-15 -2.36985044e-17  2.65405504e-01  6.96643391e+00
  1.95163929e+01]
Спектр матрицы C:  [ 0.2654055   6.96643391 19.51639286]


16. Численно посчитать определённый интеграл  3-мя методами:  
a)	Прямоугольников $\int\limits_a^b {f(x)dx \approx \Delta x\sum\limits_{k = 0}^N {f({x_k})} }$  
b)	Трапеций $\int\limits_a^b {f(x)dx \approx \frac{{\Delta x}}{2}\left( {f({x_0}) + 2\sum\limits_{k = 1}^{N - 1} {f({x_k})}  + f({x_N})} \right)}$  
c)	По правилу Симпсона  $\int\limits_a^b {f(x)dx \approx \frac{{\Delta x}}{3}\left( {f({x_0}) + 2\sum\limits_{k = 1}^{N/2 - 1} {f({x_{2k}})}  + 4\sum\limits_{k = 1}^{N/2} {f({x_{2k - 1}})}  + f({x_N})} \right)}$  


В реализации этих методов цикл for для суммирования использовать нельзя.  
Нужно посчитать значение интеграла с некоторым шагом интегрирования (например начать с 0.1), потом уменьшить его в десять раз и ещё раз посчитать и так до тех пор пока отличие в ответах будет в 5-м знаке после запятой, т.е. чтобы ошибка была меньше 1e-5. Получить ответы для 3-х разных методов и сделать соответствующие выводы.  

Далее необходимо сравнить полученные оценки с аналитическим решением (т.е. формульным, которое вы должны сами посчитать на листочке и вбить формулу-ответ).   

В качестве интеграла взять два из следующих примеров:  
- один с номером, сгенерированным случайным образом с помощью функции np.random.randint(9), в качестве seed для генератора случайных чисел взять номер своего студенческого билета. 
- второй номер - под номером 9, несобственный интерграл. Подумайте, как сделать подбор шага интегрирования адаптивным.

<table width="80%"
       align="center">
    <tr>
        <td> 0) $\int\limits_3^4 {\frac{{{x^2} + 3}}{{x - 2}}dx}$ </td>
        <td> 1) $\int\limits_{ - 2}^{ - 1} {\frac{{x + 1}}{{{x^3} - {x^2}}}dx}$ </td>
        <td> 2) $\int\limits_1^2 {\frac{{{e^{1/{x^2}}}}}{{{x^3}}}dx}$ </td>
        <td> 3) $\int\limits_1^e {\frac{{\cos (\ln x)}}{x}dx}$ </td>
        <td> 4) $\int\limits_1^e {\frac{{dx}}{{x(1 + {{\ln }^2}x)}}}$ </td>
    </tr>                
    <tr>
        <td> 5) $\int\limits_0^{\pi /2} {{{\cos }^3}\alpha \;d\alpha }$ </td>
        <td> 6) $\int\limits_0^{1/3} {c{h^2}3x\;dx}$ </td>
        <td> 7) $\int\limits_2^3 {\frac{{dy}}{{{y^2} - 2y - 8}}dy}$ </td>
        <td> 8) $\int\limits_0^2 {\frac{{2x - 1}}{{2x + 1}}dx}$ </td>
        <td> 9) $\int\limits_{3/4}^2 {\frac{{dx}}{{\sqrt {2 + 3x - 2{x^2}} }}}$ </td>
        </tr>
</table>